version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: regular_user
  MYSQL_PASSWORD: regular_pass
  MYSQL_DATABASE: futurium_exhibition_stats
  REACT_APP_SERVER_PORT: 8000
  REDIS_HOST: redis  # Adding Redis host variable for use in other services

services:
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - /home/administrator/redis/data:/data  # Optional: persistent storage for Redis
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    command: redis-server --bind 0.0.0.0

  worker:
    build: 
      context: /home/administrator/statistics_app/Exhibition_Statistics/redis/worker
      dockerfile: Dockerfile
    container_name: worker_container
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - TZ=Europe/Berlin


  # python backend 
  python_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - /etc/localtime:/backend/etc/localtime:ro
    working_dir: /backend
    environment:
      TZ: "Europe/Berlin"
      #<<: *common-variables
      #REDIS_URL: "redis://redis:6379"  # Add this line if your backend interacts with Redis

  # python backend 
  flask_dash_app:
    build:
      context: ./flask_dash_app
      dockerfile: Dockerfile
    volumes:
      - ./flask_dash_app:/flask_dash_app
      - /etc/localtime:/flask_dash_app/etc/localtime:ro
    working_dir: /flask_dash_app
    environment:
      TZ: "Europe/Berlin"
      <<: *common-variables
      REDIS_URL: "redis://redis:6379"  # Enable Dash app to communicate with Redis
    ports:
      - 8050:8050
    depends_on:
      - redis

  # mysql server
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3308:3308
    restart: unless-stopped
    volumes:
      # db schema did not work correctly when container was build and had to manually import it through php admin, check whats wrong before rebuilding this service
      #- /home/administrator/statistics_app/Exhibition_Statistics/backend/db_schema/exhibition_schema.sql:/docker-entrypoint-initdb.d/exhibition_schema.sql
      - /home/administrator/db/config:/etc/mysql/conf.d
      - /home/administrator/db/data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: unless-stopped