-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 16:27:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema futurium_exhibition_stats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema futurium_exhibition_stats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futurium_exhibition_stats` DEFAULT CHARACTER SET utf8 ;
USE `futurium_exhibition_stats` ;

-- -----------------------------------------------------
-- Table `futurium_exhibition_stats`.`scans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futurium_exhibition_stats`.`scans` (
  `scan_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scan_date` DATE NOT NULL,
  `scan_time` TIME NOT NULL,
  `scan_station_id` VARCHAR(32) NOT NULL,
  `scan_band_code` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`scan_id`),
  UNIQUE INDEX `scan_UNIQUE_combi` (`scan_date` ASC, `scan_station_id` ASC, `scan_band_code` ASC) COMMENT 'Through this index multiple scan of one band code to one station within the same day are disallowed (i.e. children at play) ' VISIBLE,
  UNIQUE INDEX `scan_id_UNIQUE` (`scan_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futurium_exhibition_stats`.`token_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futurium_exhibition_stats`.`token_stations` (
  `token_db_id` INT NOT NULL AUTO_INCREMENT,
  `tk_station_id` VARCHAR(32) NOT NULL,
  `theme_area` ENUM('human', 'tech', 'natur') NULL,
  `tk_type` ENUM('normal', 'vote', 'interactive') NULL,
  `x_coord` FLOAT NULL,
  `y_coord` FLOAT NULL,
  PRIMARY KEY (`token_db_id`),
  UNIQUE INDEX `token_db_id_UNIQUE` (`token_db_id` ASC) VISIBLE,
  UNIQUE INDEX `tk_station_id_UNIQUE` (`tk_station_id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `futurium_exhibition_stats`;

DELIMITER $$
USE `futurium_exhibition_stats`$$
CREATE DEFINER = CURRENT_USER TRIGGER `futurium_exhibition_stats`.`scans_AFTER_INSERT` AFTER INSERT ON `scans` FOR EACH ROW
BEGIN
  INSERT IGNORE INTO token_stations (tk_station_id)
  VALUES (NEW.scan_station_id);
END$$


DELIMITER ;

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
